library(shiny)

# cmd is the original codestr (also listed in tab 'script')
# as generated by one of the code_xxx() reactive-expressions
runEvalStr <- function(cmd, comment = NULL) {
  nr_warnings_start <- nrow(get.sdcMicroObj(obj$sdcObj, type = "additionalResults")$sdcMicro_warnings)
  if (is.null(nr_warnings_start)) {
    nr_warnings_start <- 0
  }

  evalAsIs <- !is.null(attributes(cmd)$evalAsIs)
  # evaluate using tryCatchFn()
  if (evalAsIs) {
    cmdeval <- gsub("sdcObj", "obj$sdcObj", cmd)
  } else {
    if (length(grep("<-", unlist(strsplit(cmd, " ")))) > 1) {
      cmdeval <- gsub("\n", "", cmd)
      cmdeval <- sub("obj[$]sdcObj <- ", "", cmdeval) # first occurence
      cmdeval <- gsub("sdcObj", "obj$sdcObj", cmd)
    } else {
      cmdeval <- gsub("sdcObj", "obj$sdcObj", cmd)
      cmdeval <- strsplit(cmdeval, "<-")[[1]][2]
    }
  }
  evalstr <- paste0("res <- sdcMicro:::tryCatchFn({", cmdeval, "})")
  # cat(evalstr,"\n")
  eval(parse(text = evalstr))
  if (!"simpleError" %in% class(res)) {
    obj$last_error <- NULL

    if (!evalAsIs) {
      obj$sdcObj <- res
      rm(res)
    }

    if (!is.null(comment)) {
      cmd <- paste0(comment, "\n", cmd)
    }
    cmd <- sub("lab=obj[$]stata_labs, ", "", cmd) # for stata export
    obj$code_anonymize <- c(obj$code_anonymize, cmd)
    # check if we have some new warnings
    current_warnings <- get.sdcMicroObj(obj$sdcObj, type = "additionalResults")$sdcMicro_warnings
    nr_new <- nrow(current_warnings)
    if (!is.null(current_warnings) && nrow(current_warnings) > nr_warnings_start) {
      obj$last_warning <- utils::tail(current_warnings, 1)
    } else {
      obj$last_warning <- NULL
    }
  } else {
    obj$last_error <- res$message
    obj$last_warning <- NULL
  }
}

# simple evaluations
runEvalStrMicrodat_no_errorchecking <- function(cmd, comment = NULL) {
  # evaluate using tryCatchFn()
  cmdeval <- gsub("inputdata", "obj$inputdata", cmd)
  eval(parse(text = cmdeval))

  if (!is.null(comment)) {
    cmd <- paste0(comment, "\n", cmd)
  }
  obj$code_read_and_modify <- c(obj$code_read_and_modify, cmd)
}

# runEvaluationString and update Objects for microdata-modifications
runEvalStrMicrodat <- function(cmd, comment = NULL) {
  # evaluate using tryCatchFn()
  # if we read an existing object from R, we need to use sub (in case the obj is called inputdata)
  is_from_df <- grep('type="rdf"', cmd)
  if (length(is_from_df) > 0) {
    cmdeval <- sub("inputdata", "obj$inputdata", cmd)
  } else {
    cmdeval <- gsub("inputdata", "obj$inputdata", cmd)
  }

  cmdeval <- strsplit(cmdeval, "<-")[[1]][2]
  evalstr <- paste0("res <- sdcMicro:::tryCatchFn({", cmdeval, "})")
  # cat("evalstr:", evalstr,"\n")
  eval(parse(text = evalstr))
  # print(str(res))
  if (!"simpleError" %in% class(res)) {
    obj$last_error <- NULL
    obj$inputdata <- res
    rm(res)
    if (!is.null(comment)) {
      cmd <- paste0(comment, "\n", cmd)
    }
    obj$code_read_and_modify <- c(obj$code_read_and_modify, cmd)
    # check if we have some new warnings
  } else {
    obj$last_error <- res$message
    obj$last_warning <- NULL
  }
}

# required code to temporarily reset strata-variable
# new_strataV: new strata variable
# ex_strataV: existing strata variable
code_reset_strata <- function(new_strataV, ex_strataV) {
  cmd1 <- cmd2 <- NA
  strata_ex <- ex_strataV
  if (!is.null(strata_ex) & is.null(new_strataV)) {
    cmd1 <- paste0("strataVar(sdcObj) <- NULL")
  } else if (is.null(strata_ex) & !is.null(new_strataV)) {
    cmd1 <- paste0("strataVar(sdcObj) <- ", dQuote(new_strataV))
  }

  # reset back to original value
  if (!is.null(strata_ex) & !is.null(new_strataV)) {
    cmd2 <- paste0("strataVar(sdcObj) <-", dQuote(ex_strataV))
  } else if (is.null(strata_ex) & !is.null(new_strataV)) {
    cmd2 <- paste0("strataVar(sdcObj) <- NULL")
  }
  out <- list(cmd1 = cmd1, cmd2 = cmd2)
}

# helper function for code-generation
# correctly 'quote' a character vector
VecToRStr <- function(v, quoted = TRUE) {
  if (quoted) {
    paste0('c("', paste(v, collapse = '","'), '")')
  } else {
    paste0("c(", paste(v, collapse = ","), ")")
  }
}

VecToRStr_txt <- function(v) {
  paste0('"', paste(v, collapse = '", "'), '"')
}

# filed file names keeping original name of uploaded file
fixUploadedFilesNames <- function(x) {
  # if (is.null(x)) {
  #   return()
  # }
  # oldNames <- x$datapath
  # newNames <- file.path(dirname(x$datapath), x$name)
  # file.rename(from = oldNames, to = newNames)
  # x$datapath <- newNames
  x
}

genObserver_menus <- function(pat = "btn_results_", n = 1, updateVal) {
  res <- paste0("observeEvent(input$", pat, n, ', {
    curid <- "', pat, n, '"
    nn <- names(input)
    nn <- nn[grep("', pat, '",nn)]
    nn <- setdiff(nn, curid)
    for (btnid in nn) {
      updateButton(session, btnid, style="default")
    }
    obj$', updateVal, ' <- "', pat, n, '"
    updateButton(session, curid, style="primary")
  });
  ')
  res
}


myActionButton <- function(inputId, label, btn.style = "", css.class = "") {
  if (btn.style %in% c("primary", "info", "success", "warning", "danger", "inverse", "link")) {
    btn.css.class <- paste("btn", btn.style, sep = "-")
  } else {
    btn.css.class <- ""
  }
  tags$button(id = inputId, type = "button", class = paste("btn action-button", btn.css.class, css.class, collapse = " "), label)
}

myErrBtn <- function(id, label, btn.style = "danger") {
  btn <- myActionButton(id, label = label, btn.style = btn.style)
  return(fluidRow(column(12, div(btn, align = "center"))))
}

# does not immediately react to user input
customTextInput <- function(inputId, label, value = "") {
  tagList(
    singleton(tags$head(tags$script(src = "sdcwww/js/customTextInputBinding.js"))),
    tags$label(label, `for` = inputId),
    tags$input(id = inputId, type = "text", value = value, class = "returnTextInput")
  )
}

msg_nodata <- function(tab_import = FALSE) {
  if (tab_import) {
    txt <- "Please select a dataset to upload"
  } else {
    txt <- "Please upload data in the Microdata tab!"
  }
  fluidRow(
    column(12, h2("No data available", align = "center")),
    column(12, strong(txt))
  )
}

# custom Summary-Function for numerical Variables
summaryfn <- function(x) {
  if (is.numeric(x)) {
    vv <- c(
      min(x, na.rm = TRUE),
      stats::quantile(x, c(0.05, 0.25, 0.5), na.rm = TRUE),
      mean(x, na.rm = TRUE),
      stats::quantile(x, c(0.75, 0.95), na.rm = TRUE), max(x, na.rm = TRUE)
    )
    names(vv) <- c("Min", "Q5", "Q25", "Median", "Mean", "Q75", "Q95", "Max")
  } else {
    vv <- as.data.frame.table(addmargins(table(x, useNA = "always")))
    vv$Freq <- as.integer(vv$Freq)
    vv$Perc <- formatC(100 * (vv$Freq / length(x)), format = "f", digits = 2)
  }
  vv
}

noInputData <- function(prefix = "btn_a_micro_", uri) {
  btn <- myActionButton(paste0(prefix, uri), label = ("Load microdata"), "primary")
  fluidRow(
    column(12, h3("No input data available!"), class = "wb-header"),
    column(12, p("Go to the Microdata tab to upload a dataset or upload a previously saved problem from the Undo tab"), class = "wb-header-hint"),
    column(12, p("Go back to the Microdata tab by clicking the button below and load a dataset."), align = "center"),
    column(12, div(btn, align = "center"))
  )
}

noSdcProblem <- function(prefix = "btn_a_setup_", uri) {
  txt <- "Go back to the Anonymize tab by clicking the button below and select variables"
  btn <- myActionButton(paste0(prefix, uri), label = ("Create an SDC problem"), "primary")
  fluidRow(
    column(12, h3("No SDC problem was specified"), class = "wb-header"),
    column(12, p("Please go to the Microdata tab to upload a dataset or upload a previously saved problem from the Reproducibility tab."), class = "wb-header-hint"),
    column(12, p(txt)),
    column(12, div(btn, align = "center"))
  )
}

# generate dynamic observers
genDynLinkObserver <- function(prefix = "btn_a_setup_", verbose = FALSE, inputId = "mainnav", selected = NULL) {
  fn <- paste0(prefix, sapply(strsplit(list.files("controllers"), "[.]"), function(x) x[1]))
  cmd <- paste0("observeEvent(input$", paste(fn, sep = ""), ", {")
  if (verbose) {
    cmd <- paste0(cmd, 'cat("', sQuote(paste(fn, sep = "")), ' was clicked ",input$', paste(fn, sep = ""), ', "times\\n");')
  }
  cmd <- paste0(cmd, "updateNavbarPage(session, inputId=", dQuote(inputId), ", selected=", dQuote(selected), ")});")
}
